export const peopleData =[{
    "id": 1,
    "Profile_picture": "http://dummyimage.com/186x100.png/ff4444/ffffff",
    "first_name": "Danny",
    "last_name": "Abbys",
    "email": "dabbys0@msn.com",
    "gender": "Female"
  }, {
    "id": 2,
    "Profile_picture": "http://dummyimage.com/153x100.png/cc0000/ffffff",
    "first_name": "Alissa",
    "last_name": "Sanney",
    "email": "asanney1@oakley.com",
    "gender": "Female"
  }, {
    "id": 3,
    "Profile_picture": "http://dummyimage.com/117x100.png/5fa2dd/ffffff",
    "first_name": "Adey",
    "last_name": "Enderle",
    "email": "aenderle2@wikipedia.org",
    "gender": "Female"
  }, {
    "id": 4,
    "Profile_picture": "http://dummyimage.com/164x100.png/dddddd/000000",
    "first_name": "Gabrielle",
    "last_name": "Desport",
    "email": "gdesport3@thetimes.co.uk",
    "gender": "Female"
  }, {
    "id": 5,
    "Profile_picture": "http://dummyimage.com/177x100.png/cc0000/ffffff",
    "first_name": "Gelya",
    "last_name": "Dei",
    "email": "gdei4@slideshare.net",
    "gender": "Female"
  }, {
    "id": 6,
    "Profile_picture": "http://dummyimage.com/207x100.png/dddddd/000000",
    "first_name": "Kareem",
    "last_name": "Broscombe",
    "email": "kbroscombe5@wordpress.org",
    "gender": "Male"
  }, {
    "id": 7,
    "Profile_picture": "http://dummyimage.com/248x100.png/dddddd/000000",
    "first_name": "Harlie",
    "last_name": "Moorrud",
    "email": "hmoorrud6@t.co",
    "gender": "Female"
  }, {
    "id": 8,
    "Profile_picture": "http://dummyimage.com/230x100.png/ff4444/ffffff",
    "first_name": "Mozes",
    "last_name": "Ghest",
    "email": "mghest7@free.fr",
    "gender": "Male"
  }, {
    "id": 9,
    "Profile_picture": "http://dummyimage.com/205x100.png/5fa2dd/ffffff",
    "first_name": "Foss",
    "last_name": "Sutherby",
    "email": "fsutherby8@taobao.com",
    "gender": "Male"
  }, {
    "id": 10,
    "Profile_picture": "http://dummyimage.com/240x100.png/ff4444/ffffff",
    "first_name": "Hurlee",
    "last_name": "Voice",
    "email": "hvoice9@amazon.co.jp",
    "gender": "Male"
  }]
  